### PR TITLE
Fix a bug with `"null"` string instead of `null` value when applying extras to event

### LINKED ISSUE #93: Setting `"null"` String instead of `null` for known key in `SentryEvent`
Current logic applies `"null"` String value for a known key before every event. 

So when we have `knownKeys = listOf("foobar")`, and we won't provide any logic in `DataProvider#provideExtrasForEvent`, we'll end up with `event.get("foobar") = "null"` which is invalid. It should be `event.get("foobar") = null`

### PR DESCRIPTION
**Pull request by wzieba**
Closes: #93

### CODE REVIEW

File: AutomatticTracks/src/main/java/com/automattic/android/tracks/crashlogging/internal/SentryCrashLogging.kt [hunk 1]
```diff
@@ -55,8 +56,11 @@ internal class SentryCrashLogging constructor(
         )
     }
 
-    private fun mergeKnownKeysWithValues(event: SentryEvent) = dataProvider.extraKnownKeys()
-        .associateWith { knownKey -> event.getExtra(knownKey).toString() }
```
Comment (wzieba) [inline AutomatticTracks/src/main/java/com/automattic/android/tracks/crashlogging/internal/SentryCrashLogging.kt:59]: This is core problem with previous implementation. When `SentryEvent` didn't have applied value for a `knownKey`, we received `null` which we later mapped to string (like `null.toString()`) so we've ended up with `"null"` instead of `null`

**Comment by wzieba** [comment]
Hi @malinajirka 👋  

can I ask you for review of this PR? It's very small and also doesn't require any any tests - unit test checks for the expected behavior and I think it's sufficient check.

**Review by malinajirka — APPROVED** [review]
Thanks @wzieba! LGTM ;)

**Comment by wzieba** [comment]
Thank you a lot, I can always count on you! 🙇
